sudo: false
language: node_js
node_js: 8
install: echo "Installation happens in the setup script"
cache:
  directories:
  - node_modules
  - server/node_modules
  - client/node_modules
  - ~/.npm
  - ~/.cache
notifications:
  email: false
branches:
  only:
  - master
before_script:
  - npx cypress verify &
script:
  - npm run setup
after_success:
- npx codecov
deploy:
  provider: script
  script: scripts/deploy-backend.sh
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: BeiaBcr1Gturc5Bc7sTMz/iYc05tI/CeT2JkADJ8N/9ATYpF1EocyOXAr5P/O0eKFNrRkaLMe7dFyv5WD4gzn30fW0R1keIUtJeg9BsXXLQNFk57KTqx2R9z9JKF70oGQMi8yqhvjCYsbT9bw9v0aJ0pNAz54jY1923ELDCkke6jjbmB7xhXmxHVhBw25/WVeohBTO+BcBS2iz/wKe1G4M2Gd/DO9EuUQl7zormzTGqg1oLsP8SNRbpoqRfPUN31iH94LTqujdK/xm2VfUfWi1GLnwxkx73TGqEZ10z+8y8+j+D/9PHcMxtidtWYO556rJsZRAD5WgYs7qsimwhG3bHQoiur0OI/yHKNoie3ldm3Pi7yXgW5qM9h9HHWxWJDSiShqBUjVgQe0Ou+CRikh19enpGCI6WhadybgZvvng3cVhaGfcPNwNOe2IaYV7nGzocBgXIX5jVTabYJpeva4Mzn2SJOjnJv8Cx63R3F9GOQTJEFXriFV8KXZa4JdhLLIReyNEPnNAWzGVYFCGqgyN5OcdfG91wGTcFQGcsWtfV+oktzT1GEKOG8ak0FR4yTeTVTBSU9G1koXtHXHy2M8EICfoVjJpOfH7dffg69QUU2offAZgZiGMabxy25jp6j+cLnRA7vQyjU4A9lwprj8bFVXOC5ntV9OyafGyUD+2Y=
